server:
  port: 8083
  tomcat:
    threads:
      max: 12
spring:
  task:
    execution:
      pool:
        max-size: 12
  datasource:
    twitch:
      driver-class-name: org.sqlite.JDBC
      url: jdbc:sqlite:data/twitch.db
      liquibase:
        change-log: classpath:changelog/changelog-twitch-master.xml
    chat:
      driver-class-name: org.sqlite.JDBC
      url: jdbc:sqlite:data/chat.db
      liquibase:
        change-log: classpath:changelog/changelog-chat-master.xml

  jpa:
    twitch:
      database-platform: org.sqlite.hibernate.dialect.SQLiteDialect
      hibernate:
        ddl-auto: none
      show-sql: true


logging:
  file: logs.log
  level:
    root: INFO

twitch:
  client-id: ${KORURG_CHAT_TWITCH_CLIENT_ID}

app:
  version: ${KORURG_CHAT_PROJECT_VERSION}

sentry:
  environment: ${KORURG_CHAT_SENTRY_ENV}
  release: ${KORURG_CHAT_PROJECT_VERSION}
  dsn: ${KORURG_CHAT_SENTRY_DSN}

  logging:
    minimum-breadcrumb-level: INFO
    minimum-event-level: ERROR
    enabled: true
  sample-rate: 1

korurg-chat:
  intervals:
    update-user-info-sec: 604800