server:
  port: 8083
  tomcat:
    threads:
      max: 12
spring:
  task:
    execution:
      pool:
        max-size: 12
  datasource:
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite:data.db
    username: admin
    password: admin

  liquibase:
    change-log: classpath:changelog/changelog-master.xml

  jpa:
    database-platform: korurg.korurgchat.config.SQLiteDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        default-schema: korurg_chat

logging:
  file: logs.log
  level:
    root: INFO
#    korurg.twitch.api : DEBUG


twitch:
  client-id: ppuramprp8enkf06eubkfnqq6k0ysi

sentry:
  dsn: https://47c5970cb0ca44b48725a03b6537558d@o4504201942925312.ingest.sentry.io/4504201945874432
  logging:
    minimum-breadcrumb-level: INFO
    minimum-event-level: ERROR
    enabled: true
  sample-rate: 1

korurg-chat:
  intervals:
    update-user-info-sec: 604800

#feign:
#  client:
#    config:
#      default:
#        loggerLevel: full