name: Build unstable release

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]
env:
  KORURG_CHAT_TWITCH_CLIENT_ID: ${{vars.KORURG_CHAT_TWITCH_CLIENT_ID}}
  KORURG_CHAT_SENTRY_ENV: ${{vars.KORURG_CHAT_SENTRY_ENV}}
  KORURG_CHAT_SENTRY_DSN: ${{vars.KORURG_CHAT_SENTRY_DSN}}


permissions:
  contents: read

jobs:
  build-and-test-unstable-release:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        ref: dev

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'corretto'

    - name: Build with Gradle
      uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
      with:
        arguments: test
        
  build-and-publish-unstable-release:
    runs-on: ubuntu-latest
    needs: build-and-test-unstable-release

    steps:
    - uses: actions/checkout@v3
      with:
        ref: dev

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'corretto'

    - name: Build with Gradle
      uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
      with:
        arguments: korurg-chat:build -x test

    - name: Zip release
      run: |
        echo "#!/bin/sh" > run-linux.sh
        echo "java -jar korurg-chat.jar -Xss1m -Xmx128m" >> run-linux.sh
        echo "start java -jar korurg-chat.jar -Xss1m -Xmx128m" > run-windows.bat
        zip -7 ./korurg-chat-unstable.zip ./run-windows.bat
        zip -7 ./korurg-chat-unstable.zip ./run-linux.sh
        zip -7 ./korurg-chat-unstable.zip ./templates
        zip -j -7 ./korurg-chat-unstable.zip ./korurg-chat/build/libs/korurg-chat.jar
      shell: bash

    - name: Create a Release
      run: |
        (hub release delete "unstable") || true
        hub release create -a "./korurg-chat-unstable.zip" -m "Unstable release" -m "Release date: $(date)" "unstable"
      shell: bash
      env:
        GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}